### ISSUE TITLE
Oursh not resetting the terminal's raw mode flag

### ISSUE THREAD

**Issue by dread-uo** [nixpulvis/oursh#36] opened 2018-10-21 17:29 UTC
After running `oursh`, it seems that the terminal width or something like that is set to a mistaken value. Sorry for the lack of a better title; I can change it later.

Example:

```
➜  oursh git:(fix_home_path) cargo run           
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s                                                                                                             
     Running `target/debug/oursh`
oursh-0.3$ exit
➜  oursh git:(fix_home_path) cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.23s                                                                                                             
                                                                  Running `target/debug/oursh`
                                                                                              oursh-0.3$ 
```

All output seems to suffer from that.

I'm using `zsh`, if it is relevant.

**Comment by nixpulvis** [comment] 2018-10-22 13:15
Ok, I don't have this issue on my machine, but I was surprised how quickly https://gitlab.redox-os.org/redox-os/termion/merge_requests/150 my PR was merged, wouldn't surprise me if it's not 100% done (plus, I still need a way to buffer output and lock the raw buffer output for background jobs).

The relevant code is in `src/repl/mod.rs`.

**Comment by nixpulvis** [comment] 2018-10-24 15:19
OK, I believe I can reproduce this. But it's an issue for me in how oursh stops and doesn't reset the terminal mode. Then all future oursh (or other programs) outputs will be messed up, unless they fix it themselves.

To reproduce, in `bash` run `oursh`, enter `sleep 5` and while that's running press <kbd>ctrl+d</kbd>, then exit the shell. The result should be a bash instance on a terminal in raw mode, and therefor not properly formatted.

**Comment by nixpulvis** [comment] 2018-10-24 18:35
Deleted my last comment, because as it turns out it's always an issue... just my shell (`fish`) expects raw mode and therefor seemed fine.

**Closed** 2018-10-24 18:38 UTC
Labels: question

**Comment by nixpulvis** [comment] 2018-10-24 18:41
@dread-uo thanks for bringing this to my attention. Let me know if this fixed your issue, otherwise we can reopen this.

And, let me know if you find anything else, or have ideas of how to implement the many remaining features.
